# Generated by Django 6.1.1 on 2026-09-06 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ecole',
            field=models.ForeignKey(blank=True, help_text='Établissement auquel appartient ce compte. Vide uniquement pour le Super Admin.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='tenants.ecole'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Administrateur'), ('admin', 'Administrateur'), ('teacher', 'Enseignant'), ('student', 'Élève'), ('parent', 'Parent')], default='student', max_length=20),
        ),
    ]
