# Generated by Django 6.1.1 on 2026-09-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_ecole_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Administrateur'), ('admin', 'Administrateur'), ('teacher', 'Enseignant'), ('student', 'Élève'), ('parent', 'Parent'), ('comptabilite', 'Comptabilité'), ('surveillance', 'Surveillance Générale')], default='student', max_length=20),
        ),
    ]
