# Generated by Django 6.1.1 on 2026-09-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_sexe'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='doit_changer_mot_de_passe',
            field=models.BooleanField(default=False, help_text='Force le changement de mot de passe à la prochaine connexion — activé à la création du compte ou après une réinitialisation par un administrateur.'),
        ),
    ]
