# Generated by Django 6.1.1 on 2026-09-09 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_doit_changer_mot_de_passe'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horodatage', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.CharField(choices=[('connexion', 'Connexion'), ('compte', 'Gestion de compte'), ('eleve', 'Élève'), ('enseignant', 'Enseignant'), ('note', 'Notes'), ('paiement', 'Paiement')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_activite', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrée du journal utilisateur',
                'verbose_name_plural': 'Journal utilisateur',
                'ordering': ['-horodatage'],
            },
        ),
    ]
