# Generated by Django 6.1.1 on 2026-09-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_journalutilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='session_id',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
    ]
