# Generated by Django 6.1.1 on 2026-09-13 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalutilisateur',
            name='appareil',
            field=models.CharField(blank=True, help_text='Résumé lisible du navigateur/appareil (ex: « Chrome sur Windows »), déduit du User-Agent.', max_length=255),
        ),
    ]
