# Generated by Django 6.1.1 on 2026-09-13 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_journalutilisateur_appareil'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='derniere_activite',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
