# Generated by Django 6.1.1 on 2026-09-18 00:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_derniere_activite'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verifie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_actif',
            field=models.BooleanField(default=False, help_text='Double authentification (code à usage unique par e-mail/SMS) à chaque connexion.'),
        ),
        migrations.AddField(
            model_name='user',
            name='telephone_verifie',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CodeOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('objectif', models.CharField(choices=[('connexion', 'Double authentification à la connexion'), ('reinitialisation', 'Réinitialisation de mot de passe'), ('verification', "Vérification d'e-mail/téléphone")], max_length=20)),
                ('cible', models.CharField(blank=True, max_length=255)),
                ('expire_le', models.DateTimeField()),
                ('utilise', models.BooleanField(default=False)),
                ('tentatives', models.PositiveSmallIntegerField(default=0)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes_otp', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-cree_le'],
                'indexes': [models.Index(fields=['user', 'objectif', 'utilise'], name='accounts_co_user_id_598434_idx')],
            },
        ),
    ]
