# Generated by Django 6.1.1 on 2026-09-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_email_verifie_user_otp_actif_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Administrateur'), ('admin', 'Administrateur'), ('directeur', 'Directeur Général'), ('teacher', 'Enseignant'), ('student', 'Élève'), ('parent', 'Parent'), ('comptabilite', 'Comptabilité'), ('surveillance', 'Surveillance Générale')], default='student', max_length=20),
        ),
    ]
