# Generated by Django 6.1.1 on 2026-09-17 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code_suppression',
            field=models.CharField(blank=True, editable=False, max_length=128),
        ),
    ]
