# Generated by Django 6.1.1 on 2026-09-30 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_code_suppression'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='acces_supprime',
            field=models.BooleanField(default=False),
        ),
    ]
