# Generated by Django 6.1.1 on 2026-10-06 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_acces_supprime'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='codes_secours',
            field=models.JSONField(blank=True, default=list, editable=False),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_actif',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_dernier_pas',
            field=models.BigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_secret',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='verrouille_jusqu_a',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.CreateModel(
            name='AppareilConnu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empreinte', models.CharField(max_length=64)),
                ('libelle', models.CharField(blank=True, max_length=255)),
                ('premiere_connexion', models.DateTimeField(auto_now_add=True)),
                ('derniere_connexion', models.DateTimeField(auto_now_add=True)),
                ('derniere_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appareils_connus', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-derniere_connexion'],
            },
        ),
        migrations.CreateModel(
            name='EvenementSecurite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('connexion_reussie', 'Connexion réussie'), ('echec_mot_de_passe', 'Échec de connexion (mot de passe)'), ('echec_2fa', 'Échec de connexion (code 2FA)'), ('connexion_bloquee', 'Tentative sur compte verrouillé'), ('compte_verrouille', 'Compte verrouillé'), ('compte_deverrouille', 'Compte déverrouillé'), ('connexion_inhabituelle', 'Connexion inhabituelle'), ('deconnexion', 'Déconnexion'), ('session_revoquee', 'Session révoquée'), ('sessions_revoquees', 'Toutes les sessions révoquées'), ('appareil_retire', 'Appareil retiré'), ('totp_active', "Application d'authentification activée"), ('totp_desactive', "Application d'authentification désactivée"), ('otp_active', 'Code par e-mail/SMS activé'), ('otp_desactive', 'Code par e-mail/SMS désactivé'), ('codes_secours_regeneres', 'Codes de secours régénérés'), ('code_secours_utilise', 'Code de secours utilisé'), ('mot_de_passe_change', 'Mot de passe changé')], max_length=30)),
                ('niveau', models.CharField(choices=[('info', 'Information'), ('avertissement', 'Avertissement'), ('critique', 'Critique')], default='info', max_length=15)),
                ('description', models.CharField(max_length=255)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('appareil', models.CharField(blank=True, max_length=255)),
                ('horodatage', models.DateTimeField(auto_now_add=True)),
                ('lu', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements_securite', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-horodatage'],
            },
        ),
        migrations.CreateModel(
            name='SessionActive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=64, unique=True)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('appareil_libelle', models.CharField(blank=True, max_length=255)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('derniere_activite', models.DateTimeField(auto_now_add=True)),
                ('expire_le', models.DateTimeField()),
                ('revoquee_le', models.DateTimeField(blank=True, null=True)),
                ('appareil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='accounts.appareilconnu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_actives', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-derniere_activite'],
            },
        ),
        migrations.AddConstraint(
            model_name='appareilconnu',
            constraint=models.UniqueConstraint(fields=('user', 'empreinte'), name='appareil_unique_par_user'),
        ),
        migrations.AddIndex(
            model_name='evenementsecurite',
            index=models.Index(fields=['user', 'type', 'horodatage'], name='accounts_ev_user_id_c8524b_idx'),
        ),
    ]
