# Generated by Django 6.1.1 on 2026-10-08 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def remplir_entrees_existantes(apps, schema_editor):
    """Entrées antérieures au journal d'audit : école, nom et rôle de l'auteur recopiés depuis
    son compte, connexions marquées comme telles."""
    JournalUtilisateur = apps.get_model("accounts", "JournalUtilisateur")
    for entree in JournalUtilisateur.objects.select_related("utilisateur").iterator():
        utilisateur = entree.utilisateur
        if utilisateur is None:
            continue
        nom = f"{utilisateur.first_name} {utilisateur.last_name}".strip() or utilisateur.username
        entree.ecole_id = utilisateur.ecole_id
        entree.utilisateur_nom = nom
        entree.utilisateur_role = utilisateur.role or ""
        if entree.categorie == "connexion":
            entree.action = "connexion"
        entree.save(update_fields=["ecole", "utilisateur_nom", "utilisateur_role", "action"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_securite_superadmin'),
        ('tenants', '0027_transaction_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalutilisateur',
            name='action',
            field=models.CharField(choices=[('creation', 'Création'), ('modification', 'Modification'), ('suppression', 'Suppression'), ('connexion', 'Connexion'), ('export', 'Export'), ('autre', 'Autre action')], default='autre', max_length=20),
        ),
        migrations.AddField(
            model_name='journalutilisateur',
            name='chemin',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='journalutilisateur',
            name='details',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='journalutilisateur',
            name='ecole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_utilisateurs', to='tenants.ecole'),
        ),
        migrations.AddField(
            model_name='journalutilisateur',
            name='methode',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='journalutilisateur',
            name='utilisateur_nom',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='journalutilisateur',
            name='utilisateur_role',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='journalutilisateur',
            name='categorie',
            field=models.CharField(choices=[('connexion', 'Connexion'), ('compte', 'Gestion de compte'), ('eleve', 'Élève'), ('enseignant', 'Enseignant'), ('note', 'Notes'), ('paiement', 'Paiement'), ('academique', 'Classes & matières'), ('presence', 'Présences'), ('communication', 'Communication'), ('bibliotheque', 'Bibliothèque'), ('transport', 'Transport'), ('cantine', 'Cantine'), ('acces', "Contrôle d'accès"), ('parametres', 'Paramètres & données'), ('autre', 'Autre')], max_length=20),
        ),
        migrations.AlterField(
            model_name='journalutilisateur',
            name='horodatage',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='journalutilisateur',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_activite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='journalutilisateur',
            index=models.Index(fields=['ecole', '-horodatage'], name='accounts_jo_ecole_i_c2f699_idx'),
        ),
        migrations.RunPython(remplir_entrees_existantes, migrations.RunPython.noop),
    ]
