# Generated by Django 6.1.1 on 2026-09-06 12:34

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ecole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='ecoles/logos/')),
                ('abonnement_mensuel', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('jour_echeance', models.PositiveSmallIntegerField(default=5, help_text='Jour du mois avant lequel le paiement du mois est dû')),
                ('jours_grace', models.PositiveSmallIntegerField(default=5, help_text="Nombre de jours de tolérance après l'échéance avant blocage de l'accès")),
                ('actif', models.BooleanField(default=True, help_text='Désactivation manuelle par le Super Admin, indépendante du statut de paiement')),
                ('date_creation', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'École',
                'verbose_name_plural': 'Écoles',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='PaiementEcole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.DateField(help_text='Premier jour du mois couvert par ce paiement')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateField(auto_now_add=True)),
                ('mode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('virement', 'Virement'), ('mobile_money', 'Mobile Money'), ('cheque', 'Chèque')], default='virement', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='tenants.ecole')),
                ('enregistre_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_ecoles_enregistres', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Paiement d'abonnement",
                'verbose_name_plural': "Paiements d'abonnement",
                'ordering': ['-mois'],
                'unique_together': {('ecole', 'mois')},
            },
        ),
    ]
