# Generated by Django 6.1.1 on 2026-09-06 13:59

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametresEcole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devise', models.CharField(default='GNF', max_length=10)),
                ('bareme_notation', models.PositiveSmallIntegerField(default=20, help_text='Note maximale utilisée pour la saisie des notes (ex: /20)')),
                ('moyenne_admission', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Moyenne minimale requise pour le passage en classe supérieure', max_digits=4)),
                ('heure_limite_ponctualite', models.TimeField(default=datetime.time(8, 15), help_text='Heure au-delà de laquelle un pointage est considéré en retard')),
                ('message_bienvenue', models.CharField(blank=True, help_text='Message affiché sur le portail (accueil élèves/parents)', max_length=300)),
                ('reglement_interieur', models.TextField(blank=True)),
                ('ecole', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parametres', to='tenants.ecole')),
            ],
            options={
                'verbose_name': "Paramètres de l'école",
                'verbose_name_plural': 'Paramètres des écoles',
            },
        ),
    ]
