# Generated by Django 6.1.1 on 2026-09-06 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_parametresecole'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horodatage', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('ecole_creee', 'École créée'), ('ecole_modifiee', 'École modifiée'), ('ecole_suspendue', 'École suspendue'), ('ecole_reactivee', 'École réactivée'), ('paiement_enregistre', 'Paiement enregistré')], max_length=30)),
                ('details', models.CharField(blank=True, max_length=255)),
                ('acteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_journalisees', to=settings.AUTH_USER_MODEL)),
                ('ecole', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal', to='tenants.ecole')),
            ],
            options={
                'verbose_name': "Entrée du journal d'activité",
                'verbose_name_plural': "Journal d'activité",
                'ordering': ['-horodatage'],
            },
        ),
    ]
