# Generated by Django 6.1.1 on 2026-09-06 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_journalactivite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalactivite',
            name='action',
            field=models.CharField(choices=[('ecole_creee', 'École créée'), ('ecole_modifiee', 'École modifiée'), ('ecole_suspendue', 'École suspendue'), ('ecole_reactivee', 'École réactivée'), ('paiement_enregistre', 'Paiement enregistré'), ('relance_envoyee', 'Relance envoyée'), ('superadmin_cree', 'Compte Super Admin créé')], max_length=30),
        ),
    ]
