# Generated by Django 6.1.1 on 2026-09-07 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_alter_journalactivite_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalactivite',
            name='action',
            field=models.CharField(choices=[('ecole_creee', 'École créée'), ('ecole_modifiee', 'École modifiée'), ('ecole_suspendue', 'École suspendue'), ('ecole_reactivee', 'École réactivée'), ('paiement_enregistre', 'Paiement enregistré'), ('relance_envoyee', 'Relance envoyée'), ('superadmin_cree', 'Compte Super Admin créé'), ('ecole_supprimee', 'École supprimée définitivement'), ('connexion_support', 'Connexion en mode support')], max_length=30),
        ),
        migrations.AlterField(
            model_name='journalactivite',
            name='ecole',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal', to='tenants.ecole'),
        ),
    ]
