# Generated by Django 6.1.1 on 2026-09-07 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_alter_journalactivite_action_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanAbonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('periodicite', models.CharField(choices=[('mensuel', 'Mensuel'), ('trimestriel', 'Trimestriel'), ('annuel', 'Annuel')], default='mensuel', max_length=15)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "Plan d'abonnement",
                'verbose_name_plural': "Plans d'abonnement",
                'ordering': ['montant'],
            },
        ),
        migrations.AddField(
            model_name='ecole',
            name='plan',
            field=models.ForeignKey(blank=True, help_text="Plan tarifaire de référence (informatif — n'affecte pas la facturation)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecoles', to='tenants.planabonnement'),
        ),
    ]
