# Generated by Django 6.1.1 on 2026-09-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_planabonnement_ecole_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='planabonnement',
            name='limite_eleves',
            field=models.PositiveIntegerField(blank=True, help_text="Nombre maximal d'élèves inclus dans ce plan — vide = illimité", null=True),
        ),
    ]
