# Generated by Django 6.1.1 on 2026-09-07 16:01

from django.db import migrations, models


def _generer_numeros_facture_existants(apps, schema_editor):
    """Attribue un numéro de facture aux paiements déjà enregistrés avant l'ajout de ce
    champ (ceux-ci n'ont pas pu passer par `PaiementEcole.save()` avec ce code)."""
    PaiementEcole = apps.get_model("tenants", "PaiementEcole")
    for paiement in PaiementEcole.objects.filter(numero_facture="").order_by("id"):
        paiement.numero_facture = f"INV-{paiement.mois.year}-{paiement.id:06d}"
        paiement.save(update_fields=["numero_facture"])


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_planabonnement_limite_eleves'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametresPlateforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_plateforme', models.CharField(default='École Manager', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='plateforme/')),
                ('email_expediteur_nom', models.CharField(default='École Manager', help_text='Nom affiché comme expéditeur des e-mails automatiques (le compte SMTP reste celui du .env)', max_length=100)),
                ('support_email', models.EmailField(blank=True, help_text='Adresse affichée aux écoles pour le support', max_length=254)),
                ('support_telephone', models.CharField(blank=True, max_length=30)),
                ('sms_actif', models.BooleanField(default=True, help_text="Coupe-circuit global : désactive l'envoi de SMS sur toute la plateforme")),
                ('maintenance_active', models.BooleanField(default=False, help_text="Bloque l'accès à l'application pour tout le monde sauf le Super Admin")),
                ('maintenance_message', models.CharField(blank=True, default='La plateforme est en maintenance. Merci de réessayer dans quelques instants.', max_length=255)),
            ],
            options={
                'verbose_name': 'Paramètres de la plateforme',
                'verbose_name_plural': 'Paramètres de la plateforme',
            },
        ),
        migrations.AddField(
            model_name='paiementecole',
            name='numero_facture',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='planabonnement',
            name='limite_administrateurs',
            field=models.PositiveIntegerField(blank=True, help_text='Nombre maximal de comptes administrateur inclus dans ce plan — vide = illimité', null=True),
        ),
        migrations.AddField(
            model_name='planabonnement',
            name='limite_enseignants',
            field=models.PositiveIntegerField(blank=True, help_text="Nombre maximal d'enseignants inclus dans ce plan — vide = illimité", null=True),
        ),
        migrations.AlterField(
            model_name='paiementecole',
            name='mode_paiement',
            field=models.CharField(choices=[('especes', 'Espèces'), ('virement', 'Virement'), ('mobile_money', 'Mobile Money (autre)'), ('orange_money', 'Orange Money'), ('mtn_money', 'MTN Mobile Money'), ('moov_money', 'Moov Money'), ('carte_bancaire', 'Carte bancaire'), ('cheque', 'Chèque')], default='virement', max_length=20),
        ),
        migrations.AlterField(
            model_name='planabonnement',
            name='limite_eleves',
            field=models.PositiveIntegerField(blank=True, help_text="Nombre maximal d'élèves actifs inclus dans ce plan — vide = illimité", null=True),
        ),
        migrations.RunPython(_generer_numeros_facture_existants, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='paiementecole',
            name='numero_facture',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
