# Generated by Django 6.1.1 on 2026-09-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_parametresplateforme_paiementecole_numero_facture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecole',
            name='directeur_nom',
            field=models.CharField(blank=True, help_text="Nom du directeur/responsable de l'établissement (informatif — distinct du compte administrateur)", max_length=150),
        ),
        migrations.AddField(
            model_name='ecole',
            name='pays',
            field=models.CharField(blank=True, default='Guinée', max_length=100),
        ),
        migrations.AddField(
            model_name='ecole',
            name='type_etablissement',
            field=models.CharField(blank=True, choices=[('primaire', 'Primaire'), ('college', 'Collège'), ('lycee', 'Lycée'), ('universite', 'Université'), ('prive', 'Établissement privé'), ('public', 'Établissement public')], max_length=20),
        ),
        migrations.AddField(
            model_name='ecole',
            name='ville',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
