# Generated by Django 6.1.1 on 2026-09-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_ecole_directeur_nom_ecole_pays_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalactivite',
            name='action',
            field=models.CharField(choices=[('ecole_creee', 'École créée'), ('ecole_modifiee', 'École modifiée'), ('ecole_suspendue', 'École suspendue'), ('ecole_reactivee', 'École réactivée'), ('paiement_enregistre', 'Paiement enregistré'), ('relance_envoyee', 'Relance envoyée'), ('superadmin_cree', 'Compte Super Admin créé'), ('ecole_supprimee', 'École supprimée définitivement'), ('connexion_support', 'Connexion en mode support'), ('mot_de_passe_reinitialise', 'Mot de passe réinitialisé')], max_length=30),
        ),
    ]
