# Generated by Django 6.1.1 on 2026-09-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_alter_journalactivite_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecole',
            name='couleur_principale',
            field=models.CharField(default='#14304f', max_length=7),
        ),
        migrations.AddField(
            model_name='ecole',
            name='couleur_secondaire',
            field=models.CharField(default='#b8860b', max_length=7),
        ),
        migrations.AddField(
            model_name='ecole',
            name='fonctionnalites_desactivees',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
