# Generated by Django 6.1.1 on 2026-09-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0011_ecole_couleur_principale_ecole_couleur_secondaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecole',
            name='modele_badge',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Classique'), (2, 'Moderne'), (3, 'Élégant'), (4, 'Compact')], default=1),
        ),
        migrations.AddField(
            model_name='ecole',
            name='modele_bulletin',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Classique'), (2, 'Moderne'), (3, 'Élégant'), (4, 'Compact')], default=1),
        ),
        migrations.AddField(
            model_name='ecole',
            name='modele_fiche_inscription',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Classique'), (2, 'Moderne'), (3, 'Élégant'), (4, 'Compact')], default=1),
        ),
        migrations.AddField(
            model_name='ecole',
            name='modele_recu',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Classique'), (2, 'Moderne'), (3, 'Élégant'), (4, 'Compact')], default=1),
        ),
    ]
