# Generated by Django 6.1.1 on 2026-09-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0012_ecole_modele_badge_ecole_modele_bulletin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecole',
            name='dpe',
            field=models.CharField(blank=True, help_text="Direction Préfectorale de l'Éducation", max_length=100, verbose_name='DPE'),
        ),
        migrations.AddField(
            model_name='ecole',
            name='dsee',
            field=models.CharField(blank=True, help_text="Direction Sous-préfectorale de l'Enseignement Élémentaire", max_length=100, verbose_name='DSEE'),
        ),
        migrations.AddField(
            model_name='ecole',
            name='ire',
            field=models.CharField(blank=True, help_text="Inspection Régionale de l'Éducation", max_length=100, verbose_name='IRE'),
        ),
        migrations.AlterField(
            model_name='ecole',
            name='modele_badge',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Classique'), (2, 'Moderne'), (3, 'Élégant'), (4, 'Compact'), (5, 'Officiel (IRE/DPE)')], default=1),
        ),
        migrations.AlterField(
            model_name='ecole',
            name='modele_bulletin',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Classique'), (2, 'Moderne'), (3, 'Élégant'), (4, 'Compact'), (5, 'Officiel (IRE/DPE)')], default=1),
        ),
        migrations.AlterField(
            model_name='ecole',
            name='modele_fiche_inscription',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Classique'), (2, 'Moderne'), (3, 'Élégant'), (4, 'Compact'), (5, 'Officiel (IRE/DPE)')], default=1),
        ),
        migrations.AlterField(
            model_name='ecole',
            name='modele_recu',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Classique'), (2, 'Moderne'), (3, 'Élégant'), (4, 'Compact'), (5, 'Officiel (IRE/DPE)')], default=1),
        ),
    ]
