# Generated by Django 6.1.1 on 2026-09-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0013_ecole_dpe_ecole_dsee_ecole_ire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecole',
            name='entete_devise',
            field=models.CharField(blank=True, default='Travail - Justice - Solidarité', help_text='Devise nationale affichée en en-tête du bulletin (segments séparés par « - »)', max_length=100),
        ),
        migrations.AddField(
            model_name='ecole',
            name='entete_ministere_1',
            field=models.CharField(blank=True, default="Ministère de l'Éducation Nationale", help_text="Première ligne de l'en-tête institutionnel du bulletin", max_length=150),
        ),
        migrations.AddField(
            model_name='ecole',
            name='entete_ministere_2',
            field=models.CharField(blank=True, default="Ministère de l'Enseignement Pré-Universitaire", help_text="Seconde ligne de l'en-tête institutionnel du bulletin (laisser vide pour la masquer)", max_length=150),
        ),
        migrations.AddField(
            model_name='ecole',
            name='entete_republique',
            field=models.CharField(blank=True, default='République de Guinée', help_text='Nom du pays affiché en en-tête du bulletin', max_length=100),
        ),
    ]
