# Generated by Django 6.1.1 on 2026-09-09 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0014_ecole_entete_devise_ecole_entete_ministere_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeleMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle', models.CharField(max_length=30)),
                ('sujet', models.CharField(blank=True, help_text="Objet de l'e-mail (le SMS n'a pas d'objet)", max_length=200)),
                ('contenu', models.TextField(help_text='Texte envoyé — utilisez les jetons entre accolades proposés pour ce type')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modeles_message', to='tenants.ecole')),
            ],
            options={
                'verbose_name': 'Modèle de message',
                'verbose_name_plural': 'Modèles de message',
                'unique_together': {('ecole', 'cle')},
            },
        ),
    ]
