# Generated by Django 6.1.1 on 2026-09-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0015_modelemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecole',
            name='modele_certificat',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Classique'), (2, 'Moderne'), (3, 'Élégant'), (4, 'Compact'), (5, 'Officiel (IRE/DPE)')], default=1),
        ),
    ]
