# Generated by Django 6.1.1 on 2026-09-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0017_renommer_plateforme_taly_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametresplateforme',
            name='email_expediteur_nom',
            field=models.CharField(default='Taly-School', help_text='Nom affiché comme expéditeur des e-mails automatiques (le compte SMTP reste celui du .env)', max_length=100),
        ),
        migrations.AlterField(
            model_name='parametresplateforme',
            name='nom_plateforme',
            field=models.CharField(default='Taly-School', max_length=100),
        ),
    ]
