# Generated by Django 6.1.1 on 2026-09-13 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0018_alter_parametresplateforme_email_expediteur_nom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecole',
            name='modele_bulletin',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Classique'), (2, 'Moderne'), (3, 'Élégant'), (4, 'Compact'), (5, 'Officiel (IRE/DPE)')], default=5),
        ),
    ]
