# Generated by Django 6.1.1 on 2026-09-22 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0020_toutes_ecoles_bulletin_officiel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionAbonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.DateField(help_text='Premier jour du mois que ce paiement doit couvrir')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payer_number', models.CharField(max_length=30)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('redirect_url', models.URLField(blank=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('reussi', 'Réussi'), ('echoue', 'Échoué')], default='en_attente', max_length=15)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('verifie_le', models.DateTimeField(blank=True, null=True)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_djomy', to='tenants.ecole')),
                ('paiement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_djomy', to='tenants.paiementecole')),
            ],
            options={
                'verbose_name': 'Transaction Djomy',
                'verbose_name_plural': 'Transactions Djomy',
                'ordering': ['-cree_le'],
            },
        ),
    ]
