# Generated by Django 6.1.1 on 2026-09-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0021_transactionabonnement'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionabonnement',
            name='nb_mois',
            field=models.PositiveSmallIntegerField(default=1, help_text="Nombre de mois couverts par ce paiement — 1 (Mensuel) ou 12 (Annuel), choisi par l'Administrateur au moment de payer"),
        ),
    ]
