# Generated by Django 6.1.1 on 2026-10-01 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0023_journal_ecole_reinitialisee'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecole',
            name='modele_attestation',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Prestige (bleu nuit, ruban et sceau doré)'), (2, 'Géométrique (blanc et bleu, médaille dorée)'), (3, 'Émeraude (blanc et vert, rosette dorée)'), (4, 'Art déco (bleu nuit, éventails dorés)')], default=1),
        ),
    ]
