# Generated by Django 6.1.1 on 2026-10-01 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0024_ecole_modele_attestation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecole',
            name='modele_badge',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Vagues (bleu, photo ronde, QR code)'), (2, 'Marine et or (code-barres)'), (3, 'Bandeau (bleu marine et jaune)'), (4, 'Université (violet et orange)')], default=1),
        ),
    ]
