# Generated by Django 6.1.1 on 2026-10-03 02:28

from datetime import date

from django.db import migrations, models


def initialiser_date_fin(apps, schema_editor):
    """Fige, pour chaque école ayant déjà des paiements, la fin d'abonnement calculée par
    l'ancien mode mensuel (dernier mois payé + périodicité du plan, au jour d'échéance) — aucune
    école ne gagne ni ne perd de jours au passage au décompte en jours. Les écoles sans paiement
    restent sans date (repli sur l'ancienne échéance du mois en cours)."""
    Ecole = apps.get_model("tenants", "Ecole")
    duree = {"trimestriel": 3, "annuel": 12}
    for ecole in Ecole.objects.select_related("plan"):
        dernier = ecole.paiements.order_by("-mois").first()
        if not dernier:
            continue
        nb_mois = duree.get(ecole.plan.periodicite, 1) if ecole.plan_id else 1
        index = dernier.mois.month - 1 + nb_mois
        mois_echeance = date(dernier.mois.year + index // 12, index % 12 + 1, 1)
        ecole.date_fin_abonnement = mois_echeance.replace(day=min(ecole.jour_echeance, 28))
        ecole.save(update_fields=["date_fin_abonnement"])


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0025_ecole_modele_badge_choix'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecole',
            name='date_fin_abonnement',
            field=models.DateField(blank=True, help_text="Dernier jour couvert par l'abonnement payé", null=True),
        ),
        migrations.RunPython(initialiser_date_fin, migrations.RunPython.noop),
    ]
