# Generated by Django 6.1.1 on 2026-10-03 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0026_date_fin_abonnement'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionabonnement',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_djomy', to='tenants.planabonnement'),
        ),
        migrations.AlterField(
            model_name='transactionabonnement',
            name='nb_mois',
            field=models.PositiveSmallIntegerField(default=1, help_text="Nombre de mois couverts par ce paiement — 1 (Mensuel), 3 (Trimestriel) ou 12 (Annuel), selon le plan choisi par l'Administrateur au moment de payer"),
        ),
    ]
