# Generated by Django 6.1.1 on 2026-09-06 01:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: Trimestre 1', max_length=50)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodes', to='academics.anneescolaire')),
            ],
            options={
                'ordering': ['date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_evaluation', models.CharField(choices=[('devoir', 'Devoir'), ('composition', 'Composition'), ('interrogation', 'Interrogation'), ('projet', 'Projet')], default='devoir', max_length=20)),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('coefficient', models.PositiveIntegerField(default=1)),
                ('date', models.DateField()),
                ('commentaire', models.CharField(blank=True, max_length=255)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='people.eleveprofile')),
                ('enseignant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_saisies', to=settings.AUTH_USER_MODEL)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='academics.matiere')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='grades.periode')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
