# Generated by Django 6.1.1 on 2026-10-01 01:15

import acces.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0023_journal_ecole_reinitialisee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex : Portail principal', max_length=100)),
                ('type', models.CharField(choices=[('qr', 'Lecteur QR code'), ('rfid', 'Lecteur RFID / badge'), ('biometrie', 'Biométrie (empreinte, visage)'), ('camera', 'Caméra (reconnaissance)'), ('porte', 'Contrôleur de porte / tourniquet'), ('borne', 'Borne navigateur (PC / tablette)')], default='qr', max_length=12)),
                ('sens', models.CharField(choices=[('auto', 'Automatique (entrée puis sortie)'), ('entree', 'Entrées uniquement'), ('sortie', 'Sorties uniquement')], default='auto', max_length=8)),
                ('cle', models.CharField(default=acces.models._nouvelle_cle, editable=False, max_length=64, unique=True)),
                ('actif', models.BooleanField(default=True)),
                ('derniere_activite', models.DateTimeField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipements_acces', to='tenants.ecole')),
            ],
            options={
                'verbose_name': "Équipement d'accès",
                'verbose_name_plural': "Équipements d'accès",
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='CarteAcces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(help_text='Numéro lu par le lecteur RFID', max_length=100)),
                ('actif', models.BooleanField(default=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartes_acces', to='tenants.ecole')),
                ('personne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartes_acces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Carte d'accès",
                'verbose_name_plural': "Cartes d'accès",
                'ordering': ['-cree_le'],
                'constraints': [models.UniqueConstraint(fields=('ecole', 'uid'), name='unique_carte_acces_ecole_uid')],
            },
        ),
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_affiche', models.CharField(blank=True, max_length=150)),
                ('role', models.CharField(blank=True, max_length=20)),
                ('classe', models.CharField(blank=True, max_length=50)),
                ('sens', models.CharField(blank=True, choices=[('entree', 'Entrée'), ('sortie', 'Sortie')], max_length=6)),
                ('horodatage', models.DateTimeField(default=django.utils.timezone.now)),
                ('methode', models.CharField(choices=[('qr', 'QR code'), ('rfid', 'Carte RFID'), ('matricule', 'Matricule (biométrie, caméra, saisie)'), ('inconnu', 'Inconnu')], default='inconnu', max_length=10)),
                ('identifiant_lu', models.CharField(blank=True, max_length=255)),
                ('autorise', models.BooleanField(default=True)),
                ('motif_refus', models.CharField(blank=True, max_length=150)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passages', to='tenants.ecole')),
                ('equipement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passages', to='acces.equipement')),
                ('personne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Passage',
                'verbose_name_plural': 'Passages',
                'ordering': ['-horodatage'],
                'indexes': [models.Index(fields=['ecole', 'horodatage'], name='acces_passa_ecole_i_9ef332_idx'), models.Index(fields=['personne', 'horodatage'], name='acces_passa_personn_ce8721_idx')],
            },
        ),
    ]
