# Generated by Django 6.1.1 on 2026-09-06 08:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_alerteparent_elevebadge_grouperevision_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnseignantBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('actif', models.BooleanField(default=True)),
                ('emis_le', models.DateTimeField(auto_now_add=True)),
                ('enseignant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='badge', to='people.enseignantprofile')),
            ],
        ),
    ]
