# Generated by Django 6.1.1 on 2026-09-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_enseignantbadge'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleveprofile',
            name='actif',
            field=models.BooleanField(default=True, help_text="Faux si l'élève ne se réinscrit pas (parti, changé d'école...)"),
        ),
        migrations.AddField(
            model_name='eleveprofile',
            name='date_sortie',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eleveprofile',
            name='motif_sortie',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
