# Generated by Django 6.1.1 on 2026-09-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_eleveprofile_actif_eleveprofile_date_sortie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paieenseignant',
            name='mode_calcul',
            field=models.CharField(choices=[('fixe', 'Salaire fixe'), ('horaire', 'Taux horaire')], default='fixe', max_length=10),
        ),
        migrations.AddField(
            model_name='paieenseignant',
            name='nombre_heures',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Nombre d'heures enseignées dans le mois (mode taux horaire)", max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='paieenseignant',
            name='taux_horaire',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant payé par heure enseignée (mode taux horaire)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='paieenseignant',
            name='salaire_base',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Utilisé si mode de calcul = salaire fixe', max_digits=10),
        ),
    ]
