# Generated by Django 6.1.1 on 2026-09-06 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_paieenseignant_mode_calcul_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Élève'), ('assistant', 'Assistant')], max_length=10)),
                ('contenu', models.TextField()),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_ia', to='people.eleveprofile')),
            ],
            options={
                'verbose_name': 'Message assistant IA',
                'verbose_name_plural': 'Messages assistant IA',
                'ordering': ['cree_le'],
            },
        ),
    ]
