# Generated by Django 6.1.1 on 2026-09-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_messageia'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleveprofile',
            name='nom_mere',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='eleveprofile',
            name='nom_pere',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='eleveprofile',
            name='nom_tuteur',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='eleveprofile',
            name='regime',
            field=models.CharField(choices=[('externe', 'Externe'), ('demi_pension', 'Demi-pension'), ('interne', 'Interne')], default='externe', max_length=20),
        ),
        migrations.AddField(
            model_name='eleveprofile',
            name='statut_inscription',
            field=models.CharField(choices=[('nouveau', 'Nouvelle inscription'), ('reinscription', 'Réinscription'), ('transfert', 'Transfert')], default='nouveau', max_length=20),
        ),
    ]
