# Generated by Django 6.1.1 on 2026-09-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_eleveprofile_nom_mere_eleveprofile_nom_pere_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleveprofile',
            name='categorie_paiement',
            field=models.CharField(choices=[('standard', "Standard — paie l'intégralité de la mensualité"), ('fondation_50', 'Fondation — 50% de réduction sur la mensualité'), ('fondation_gratuit', 'Fondation — exonéré de mensualité'), ('inscription_seulement', 'Inscription/réinscription uniquement (pas de mensualité)')], default='standard', max_length=25),
        ),
        migrations.AddField(
            model_name='eleveprofile',
            name='reduction_fidelite_mensualite',
            field=models.BooleanField(default=False, help_text="Réduction de 5% sur la mensualité, accordée manuellement par l'administration aux élèves réguliers dans leurs paiements. Se cumule avec la catégorie de paiement (ex: Fondation 50% + fidélité = 47,5% du tarif standard)."),
        ),
    ]
