# Generated by Django 6.1.1 on 2026-09-10 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_classe_cycle'),
        ('people', '0008_eleveprofile_categorie_paiement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueClasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_classes_eleves', to='academics.anneescolaire')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_eleves', to='academics.classe')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_classes', to='people.eleveprofile')),
            ],
            options={
                'verbose_name': 'Historique de classe',
                'verbose_name_plural': 'Historique de classe',
                'ordering': ['-annee_scolaire__date_debut'],
                'unique_together': {('eleve', 'annee_scolaire')},
            },
        ),
    ]
