# Generated by Django 6.1.1 on 2026-09-30 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_backfill_historique_classe'),
        ('tenants', '0023_journal_ecole_reinitialisee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('motif', models.CharField(choices=[('resultats', 'Résultats scolaires'), ('comportement', 'Comportement'), ('absences', 'Absences / retards'), ('orientation', 'Orientation'), ('autre', 'Autre')], default='resultats', max_length=20)),
                ('message', models.CharField(blank=True, help_text='Précision du parent', max_length=500)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('accepte', 'Accepté'), ('refuse', 'Refusé'), ('annule', 'Annulé')], default='en_attente', max_length=12)),
                ('reponse', models.CharField(blank=True, help_text="Message de l'enseignant (ex: autre créneau proposé)", max_length=500)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('repondu_le', models.DateTimeField(blank=True, null=True)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='tenants.ecole')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='people.eleveprofile')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous_recus', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous_demandes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rendez-vous',
                'verbose_name_plural': 'Rendez-vous',
                'ordering': ['-date', '-heure'],
            },
        ),
    ]
