# Generated by Django 6.1.1 on 2026-10-05 01:28

from django.db import migrations, models


def calculer_fratries_existantes(apps, schema_editor):
    """Applique la réduction fratrie aux familles déjà inscrites (voir people/fratrie.py)."""
    from people.fratrie import recalculer_exoneration_fratrie

    EleveProfile = apps.get_model("people", "EleveProfile")
    parents = EleveProfile.objects.filter(parent__isnull=False, actif=True).values_list("parent_id", flat=True).distinct()
    for parent_id in parents:
        recalculer_exoneration_fratrie(parent_id, modele=EleveProfile)


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0011_rendez_vous'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleveprofile',
            name='exonere_fratrie',
            field=models.BooleanField(default=False, editable=False, help_text="Enfant de la classe la plus basse d'un parent qui a au moins 6 enfants inscrits : exonéré de mensualité."),
        ),
        migrations.RunPython(calculer_fratries_existantes, migrations.RunPython.noop),
    ]
