# Generated by Django 6.1.1 on 2026-09-08 16:52

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0008_eleveprofile_categorie_paiement_and_more'),
        ('tenants', '0010_alter_journalactivite_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: Formule standard', max_length=100)),
                ('responsable_nom', models.CharField(blank=True, max_length=150)),
                ('responsable_telephone', models.CharField(blank=True, help_text='Visible par les élèves/parents inscrits à cette formule, pour le joindre directement.', max_length=30)),
                ('prix', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('capacite', models.PositiveIntegerField(default=100)),
                ('heure_service', models.TimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('token_agent', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ecole', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formules_cantine', to='tenants.ecole')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='InscriptionCantine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(auto_now_add=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions_cantine', to='people.eleveprofile')),
                ('formule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='cantine.formule')),
            ],
            options={
                'ordering': ['formule__nom'],
                'unique_together': {('eleve', 'formule')},
            },
        ),
        migrations.CreateModel(
            name='PointageCantine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horodatage', models.DateTimeField(auto_now_add=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pointages_cantine', to='people.eleveprofile')),
                ('formule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pointages', to='cantine.formule')),
            ],
            options={
                'verbose_name': 'Pointage cantine',
                'verbose_name_plural': 'Pointages cantine',
                'ordering': ['-horodatage'],
            },
        ),
        migrations.CreateModel(
            name='TicketCantine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.DateField(help_text='Premier jour du mois couvert par ce ticket')),
                ('montant', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('paye', models.BooleanField(default=False)),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('qr_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='cantine.inscriptioncantine')),
            ],
            options={
                'verbose_name': 'Ticket de cantine',
                'verbose_name_plural': 'Tickets de cantine',
                'ordering': ['-mois'],
                'unique_together': {('inscription', 'mois')},
            },
        ),
    ]
