# Generated by Django 6.1.1 on 2026-09-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reunion',
            name='avec_video',
            field=models.BooleanField(default=True),
        ),
    ]
