# Generated by Django 6.1.1 on 2026-09-06 01:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='professeur_principal',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_dirigees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creneau',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='academics.classe'),
        ),
        migrations.AddField(
            model_name='enseignement',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enseignements', to='academics.classe'),
        ),
        migrations.AddField(
            model_name='enseignement',
            name='enseignant',
            field=models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='enseignements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creneau',
            name='enseignement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='academics.enseignement'),
        ),
        migrations.AddField(
            model_name='enseignement',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enseignements', to='academics.matiere'),
        ),
        migrations.AlterUniqueTogether(
            name='classe',
            unique_together={('nom', 'annee_scolaire')},
        ),
        migrations.AlterUniqueTogether(
            name='enseignement',
            unique_together={('matiere', 'classe')},
        ),
    ]
