# Generated by Django 6.1.1 on 2026-09-06 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anneescolaire',
            name='ecole',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annees_scolaires', to='tenants.ecole'),
        ),
        migrations.AddField(
            model_name='matiere',
            name='ecole',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='tenants.ecole'),
        ),
        migrations.AlterField(
            model_name='anneescolaire',
            name='libelle',
            field=models.CharField(help_text='Ex: 2025-2026', max_length=20),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='anneescolaire',
            unique_together={('ecole', 'libelle')},
        ),
        migrations.AlterUniqueTogether(
            name='matiere',
            unique_together={('ecole', 'code')},
        ),
    ]
