# Generated by Django 6.1.1 on 2026-09-08 13:25

from django.db import migrations, models


def _affecter_cycles_existants(apps, schema_editor):
    """Devine et affecte le cycle de toutes les classes déjà en base, à partir de leur
    niveau — pour que les écoles existantes n'aient pas de classes/élèves sans cycle."""
    from academics.models import deviner_cycle

    Classe = apps.get_model("academics", "Classe")
    for classe in Classe.objects.all():
        cycle = deviner_cycle(classe.niveau)
        if cycle:
            classe.cycle = cycle
            classe.save(update_fields=["cycle"])


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_anneescolaire_ecole_matiere_ecole_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='cycle',
            field=models.CharField(blank=True, choices=[('prescolaire', 'Préscolaire'), ('primaire', 'Primaire'), ('college', 'Collège'), ('lycee', 'Lycée')], help_text='Regroupement pédagogique (Préscolaire/Primaire/Collège/Lycée) — deviné automatiquement depuis le niveau si laissé vide, modifiable manuellement.', max_length=20),
        ),
        migrations.RunPython(_affecter_cycles_existants, migrations.RunPython.noop),
    ]
