# Generated by Django 6.1.1 on 2026-09-30 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_classe_cycle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapitreProgramme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('titre', models.CharField(max_length=200)),
                ('heures_prevues', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('statut', models.CharField(choices=[('a_faire', 'À faire'), ('en_cours', 'En cours'), ('termine', 'Terminé')], default='a_faire', max_length=10)),
                ('date_realisation', models.DateField(blank=True, help_text='Date à laquelle le chapitre a été terminé', null=True)),
                ('commentaire', models.CharField(blank=True, max_length=255)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapitres_programme', to='academics.classe')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapitres_programme', to='academics.matiere')),
                ('realise_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chapitres_realises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chapitre de programme',
                'verbose_name_plural': 'Chapitres de programme',
                'ordering': ['classe', 'matiere', 'ordre', 'id'],
            },
        ),
    ]
