# Generated by Django 6.1.1 on 2026-09-06 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: Ligne 1 — Centre-ville', max_length=100)),
                ('chauffeur_nom', models.CharField(blank=True, max_length=150)),
                ('vehicule_immatriculation', models.CharField(blank=True, max_length=30)),
                ('capacite', models.PositiveIntegerField(default=30)),
                ('heure_depart', models.TimeField(blank=True, null=True)),
                ('heure_retour', models.TimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='AffectationTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_montee', models.CharField(blank=True, max_length=150)),
                ('date_debut', models.DateField(auto_now_add=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations_transport', to='people.eleveprofile')),
                ('trajet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='transport.trajet')),
            ],
            options={
                'ordering': ['trajet__nom'],
                'unique_together': {('eleve', 'trajet')},
            },
        ),
    ]
