# Generated by Django 6.1.1 on 2026-09-06, hand-edited to safely add a unique field
# (token_chauffeur) to a table that already has rows: add it nullable first, backfill a
# distinct uuid4 per existing row in Python, then tighten the constraint.
import uuid

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def backfill_tokens_chauffeur(apps, schema_editor):
    Trajet = apps.get_model("transport", "Trajet")
    for trajet in Trajet.objects.filter(token_chauffeur__isnull=True):
        trajet.token_chauffeur = uuid.uuid4()
        trajet.save(update_fields=["token_chauffeur"])


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_paieenseignant_mode_calcul_and_more'),
        ('transport', '0002_trajet_ecole'),
    ]

    operations = [
        migrations.AddField(
            model_name='trajet',
            name='derniere_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='trajet',
            name='derniere_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='trajet',
            name='position_maj_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trajet',
            name='token_chauffeur',
            field=models.UUIDField(null=True, editable=False, unique=True),
        ),
        migrations.RunPython(backfill_tokens_chauffeur, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='trajet',
            name='token_chauffeur',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.CreateModel(
            name='PointageTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_evenement', models.CharField(choices=[('montee', 'Montée'), ('descente', 'Descente')], max_length=10)),
                ('horodatage', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pointages_transport', to='people.eleveprofile')),
                ('trajet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pointages', to='transport.trajet')),
            ],
            options={
                'verbose_name': 'Pointage transport',
                'verbose_name_plural': 'Pointages transport',
                'ordering': ['-horodatage'],
            },
        ),
        migrations.CreateModel(
            name='TicketBus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.DateField(help_text='Premier jour du mois couvert par ce ticket')),
                ('montant', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('paye', models.BooleanField(default=False)),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('qr_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('affectation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='transport.affectationtransport')),
            ],
            options={
                'verbose_name': 'Ticket de bus',
                'verbose_name_plural': 'Tickets de bus',
                'ordering': ['-mois'],
                'unique_together': {('affectation', 'mois')},
            },
        ),
    ]
