# Generated by Django 6.1.1 on 2026-09-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_trajet_derniere_latitude_trajet_derniere_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trajet',
            name='chauffeur_telephone',
            field=models.CharField(blank=True, help_text='Visible par les élèves/parents affectés à ce trajet, pour le joindre directement.', max_length=30),
        ),
    ]
