# Generated by Django 6.1.1 on 2026-09-06 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('statut', models.CharField(choices=[('present', 'Présent'), ('absent', 'Absent'), ('retard', 'Retard')], default='present', max_length=10)),
                ('justifie', models.BooleanField(default=False)),
                ('motif', models.CharField(blank=True, max_length=255)),
                ('creneau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presences', to='academics.creneau')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='people.eleveprofile')),
                ('enregistre_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presences_enregistrees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('eleve', 'date', 'creneau')},
            },
        ),
    ]
