# Generated by Django 6.1.1 on 2026-09-06 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('people', '0005_paieenseignant_mode_calcul_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JustificatifAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_absence', models.DateField()),
                ('motif', models.CharField(choices=[('maladie', 'Maladie'), ('autre', 'Autre motif')], default='autre', max_length=10)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('piece_jointe', models.FileField(blank=True, null=True, upload_to='justificatifs/')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté')], default='en_attente', max_length=12)),
                ('commentaire_traitement', models.CharField(blank=True, max_length=255)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justificatifs', to='people.eleveprofile')),
                ('soumis_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='justificatifs_soumis', to=settings.AUTH_USER_MODEL)),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='justificatifs_traites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Justificatif d'absence",
                'verbose_name_plural': "Justificatifs d'absence",
                'ordering': ['-cree_le'],
            },
        ),
    ]
