# Generated by Django 6.1.1 on 2026-09-06 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='typefrais',
            name='ecole',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='types_frais', to='tenants.ecole'),
        ),
    ]
