# Generated by Django 6.1.1 on 2026-09-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_typefrais_ecole'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='mois',
            field=models.DateField(blank=True, help_text='Mois de scolarité couvert par ce paiement (uniquement pour un frais mensuel) — premier jour du mois', null=True),
        ),
        migrations.AddField(
            model_name='typefrais',
            name='est_mensuel',
            field=models.BooleanField(default=False, help_text="Frais récurrent chaque mois (ex: scolarité mensuelle) — active le suivi mois par mois de l'élève"),
        ),
    ]
