# Generated by Django 6.1.1 on 2026-09-07 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_anneescolaire_ecole_matiere_ecole_and_more'),
        ('payments', '0003_paiement_mois_typefrais_est_mensuel'),
        ('tenants', '0009_ecole_directeur_nom_ecole_pays_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarifClasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifs_classe', to='academics.anneescolaire')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifs_frais', to='academics.classe')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifs_classe', to='tenants.ecole')),
                ('type_frais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifs_classe', to='payments.typefrais')),
            ],
            options={
                'verbose_name': 'Tarif par classe',
                'verbose_name_plural': 'Tarifs par classe',
                'ordering': ['classe__niveau', 'classe__nom', 'type_frais__nom'],
                'unique_together': {('type_frais', 'classe', 'annee_scolaire')},
            },
        ),
    ]
