# Generated by Django 6.1.1 on 2026-09-10 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_tarifclasse'),
    ]

    operations = [
        migrations.AddField(
            model_name='frais',
            name='facteur_applique',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
    ]
