# Generated by Django 6.1.1 on 2026-09-10 16:47

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_frais_facteur_applique'),
        ('tenants', '0015_modelemessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, help_text='Date effective de la dépense (modifiable — saisie possible a posteriori)')),
                ('categorie', models.CharField(choices=[('fournitures', 'Fournitures scolaires'), ('entretien', 'Entretien / Réparations'), ('salaires', 'Salaires (hors enseignants)'), ('factures', 'Eau / Électricité / Internet'), ('transport', 'Transport'), ('restauration', 'Restauration / Cantine'), ('evenement', 'Événement scolaire'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('motif', models.CharField(max_length=255)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('cheque', 'Chèque'), ('virement', 'Virement'), ('mobile_money', 'Mobile Money')], default='especes', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('responsable', models.CharField(help_text='Personne responsable ayant autorisé/émis cette dépense', max_length=150)),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='depenses/')),
                ('commentaire', models.CharField(blank=True, max_length=255)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to='tenants.ecole')),
                ('enregistre_par', models.ForeignKey(help_text="Utilisateur ayant saisi la dépense dans l'application (traçabilité, distinct du responsable ci-dessus)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses_enregistrees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
