# Generated by Django 6.1.1 on 2026-09-10 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_depense'),
        ('tenants', '0016_ecole_modele_certificat'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieDepense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories_depense', to='tenants.ecole')),
            ],
            options={
                'verbose_name': 'Catégorie de dépense',
                'verbose_name_plural': 'Catégories de dépense',
                'ordering': ['nom'],
                'unique_together': {('ecole', 'nom')},
            },
        ),
        migrations.AlterField(
            model_name='depense',
            name='categorie',
            field=models.ForeignKey(help_text="Catégories gérées par l'établissement — voir CategorieDepenseViewSet", on_delete=django.db.models.deletion.PROTECT, related_name='depenses', to='payments.categoriedepense'),
        ),
    ]
