# Generated by Django 6.1.1 on 2026-09-13 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_seed_categories_depense'),
    ]

    operations = [
        migrations.AddField(
            model_name='typefrais',
            name='periodicite',
            field=models.CharField(choices=[('mensuel', 'Mensuel'), ('trimestriel', 'Trimestriel'), ('annuel', 'Annuel'), ('autre', 'Autre / ponctuel')], default='autre', max_length=20),
        ),
    ]
