# Generated by Django 6.1.1 on 2026-09-13 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
        ('payments', '0010_backfill_periodicite'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='periode',
            field=models.ForeignKey(blank=True, help_text='Tranche couverte par ce paiement (uniquement pour un frais de périodicité Tranche)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements', to='grades.periode'),
        ),
        migrations.AlterField(
            model_name='typefrais',
            name='periodicite',
            field=models.CharField(choices=[('mensuel', 'Mensuel'), ('trimestriel', 'Tranche'), ('annuel', 'Annuel'), ('autre', 'Autre / ponctuel')], default='autre', max_length=20),
        ),
    ]
