# Generated by Django 6.1.1 on 2026-09-14 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_paiement_periode_tranche'),
    ]

    operations = [
        migrations.AddField(
            model_name='typefrais',
            name='usage',
            field=models.CharField(choices=[('standard', 'Standard'), ('inscription', "Frais d'inscription (nouvel élève)"), ('reinscription', 'Frais de réinscription')], default='standard', max_length=20),
        ),
    ]
