# Generated by Django 6.1.1 on 2026-10-05 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_typefrais_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='frais',
            name='mois',
            field=models.DateField(blank=True, null=True),
        ),
    ]
