# Generated by Django 5.0.6

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('cible_role', models.CharField(choices=[('all', 'Tout le monde'), ('admin', 'Administrateurs'), ('teacher', 'Enseignants'), ('student', 'Élèves'), ('parent', 'Parents')], default='all', max_length=20)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('epingle', models.BooleanField(default=False)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annonces', to=settings.AUTH_USER_MODEL)),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to='academics.classe')),
            ],
            options={
                'ordering': ['-epingle', '-date_publication'],
            },
        ),
    ]
