# Generated by Django 6.1.1 on 2026-09-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_annonce_ecole'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='envoyer_email',
            field=models.BooleanField(default=False, help_text='Envoyer aussi cette annonce par e-mail aux destinataires'),
        ),
        migrations.AddField(
            model_name='annonce',
            name='envoyer_sms',
            field=models.BooleanField(default=False, help_text='Envoyer aussi cette annonce par SMS aux destinataires'),
        ),
        migrations.AddField(
            model_name='annonce',
            name='notifications_envoyees',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
