# Generated by Django 6.1.1 on 2026-09-06 02:41

import messaging.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to=messaging.models.message_upload_path),
        ),
        migrations.AddField(
            model_name='message',
            name='type_message',
            field=models.CharField(choices=[('texte', 'Texte'), ('vocal', 'Message vocal'), ('fichier', 'Pièce jointe')], default='texte', max_length=10),
        ),
        migrations.AlterField(
            model_name='message',
            name='contenu',
            field=models.TextField(blank=True),
        ),
    ]
