# Generated by Django 6.1.1 on 2026-09-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SauvegardeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_lancement', models.DateTimeField(auto_now_add=True)),
                ('fichier', models.CharField(blank=True, help_text='Chemin du fichier de sauvegarde généré', max_length=255)),
                ('taille_octets', models.BigIntegerField(default=0)),
                ('duree_secondes', models.FloatField(default=0)),
                ('statut', models.CharField(choices=[('succes', 'Succès'), ('echec', 'Échec')], default='succes', max_length=10)),
                ('message', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'Sauvegarde',
                'verbose_name_plural': 'Sauvegardes',
                'ordering': ['-date_lancement'],
            },
        ),
    ]
