# Generated by Django 6.1.1 on 2026-09-30 21:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('people', '0010_backfill_historique_classe'),
        ('tenants', '0023_journal_ecole_reinitialisee'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentOfficiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('type', models.CharField(choices=[('bulletin', 'Bulletin scolaire'), ('certificat_scolarite', 'Certificat de scolarité')], max_length=30)),
                ('reference', models.CharField(help_text="Ex: « periode:3 » ou « annee:2 » — regroupe les versions d'un même document", max_length=60)),
                ('empreinte', models.CharField(help_text='SHA-256 du contenu enregistré', max_length=64)),
                ('donnees', models.JSONField(default=dict)),
                ('emis_le', models.DateTimeField(auto_now_add=True)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_officiels', to='tenants.ecole')),
                ('eleve', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_officiels', to='people.eleveprofile')),
            ],
            options={
                'verbose_name': 'Document officiel',
                'verbose_name_plural': 'Documents officiels',
                'ordering': ['-emis_le'],
                'indexes': [models.Index(fields=['type', 'eleve', 'reference'], name='core_docume_type_e4be2a_idx')],
            },
        ),
    ]
