# Generated by Django 6.1.1 on 2026-09-30 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_chapitre_programme'),
        ('core', '0002_document_officiel'),
        ('tenants', '0023_journal_ecole_reinitialisee'),
    ]

    operations = [
        migrations.CreateModel(
            name='RapportAnnuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='rapports_annuels/')),
                ('genere_le', models.DateTimeField(auto_now=True)),
                ('automatique', models.BooleanField(default=False, help_text="Généré par la tâche de fin d'année (sinon à la demande)")),
                ('provisoire', models.BooleanField(default=False, help_text="Généré avant la fin de l'année scolaire")),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports_annuels', to='academics.anneescolaire')),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports_annuels', to='tenants.ecole')),
            ],
            options={
                'verbose_name': 'Rapport annuel',
                'verbose_name_plural': 'Rapports annuels',
                'ordering': ['-annee_scolaire__date_debut'],
                'constraints': [models.UniqueConstraint(fields=('ecole', 'annee_scolaire'), name='unique_rapport_annuel_ecole_annee')],
            },
        ),
    ]
