# Generated by Django 6.1.1 on 2026-10-03 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rapport_annuel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sauvegardelog',
            name='statut',
            field=models.CharField(choices=[('succes', 'Succès'), ('echec', 'Échec'), ('en_cours', 'En cours')], default='succes', max_length=10),
        ),
    ]
