# Generated by Django 6.1.1 on 2026-10-07 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sauvegarde_en_cours'),
        ('tenants', '0027_transaction_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationSauvegardeEcole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('sauvegarde', 'Sauvegarde'), ('restauration', 'Restauration')], max_length=15)),
                ('origine', models.CharField(choices=[('manuelle', 'Manuelle'), ('avant_restauration', 'Automatique (avant restauration)'), ('importee', 'Fichier importé')], default='manuelle', max_length=20)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('succes', 'Succès'), ('echec', 'Échec')], default='en_cours', max_length=10)),
                ('date_lancement', models.DateTimeField(auto_now_add=True)),
                ('fichier', models.CharField(blank=True, help_text="Nom de l'archive dans backups/ecoles/<école>/", max_length=255)),
                ('taille_octets', models.BigIntegerField(default=0)),
                ('duree_secondes', models.FloatField(default=0)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('resume', models.JSONField(blank=True, default=dict)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations_sauvegarde', to='tenants.ecole')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurations', to='core.operationsauvegardeecole')),
            ],
            options={
                'verbose_name': "Sauvegarde d'école",
                'verbose_name_plural': "Sauvegardes d'école",
                'ordering': ['-date_lancement', '-id'],
            },
        ),
    ]
